DROP DATABASE IF EXISTS upost;

CREATE DATABASE upost;

DROP DATABASE IF EXISTS users CASCADE;

CREATE TABLE users (

	userId INT PRIMARY KEY AUTO_INCREMENT,
	userName VARCHAR(255) UNIQUE NOT NULL,
	password VARCHAR(255) NOT NULL
);
